<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="rrbot" params="parent prefix *origin">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1" /> <!-- Arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Length of finger base -->
  <xacro:property name="height2" value="1" /> <!-- Length of middle finger segment -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space between top of beam and each joint -->

  <joint name="${prefix}base_joint" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${parent}"/>
    <child link="${prefix}base_link" />
  </joint>

  <!-- Base Link -->
  <link name="${prefix}base_link">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width*4} ${width*10} ${height1}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- Finger 1 Base Link -->
  <link name="${prefix}finger1_base">
    <!-- Collision properties -->
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <!-- Visual properties -->
    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width*4} ${width*10} ${height1}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <!-- Inertial properties -->
    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>


  <!-- Joint for Finger 1 -->
  <joint name="${prefix}joint_finger1" type="revolute">
    <parent link="${prefix}base_link"/> <!-- Link to which the joint is connected -->
    <child link="${prefix}finger1_base"/> <!-- Link that the joint connects to -->
    
    <!-- Joint origin and axis -->
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>

    <!-- Joint dynamics (optional) -->
    <dynamics damping="0.7"/>

    <!-- Joint limits -->
    <limit effort="100" velocity="1.0" lower="-3.14" upper="3.14"/>
  </joint>

  <!-- Finger 1 Middle Link -->
  <link name="${prefix}finger1_middle">
    <!-- Collision properties -->
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <!-- Visual properties -->
    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>

    <!-- Inertial properties -->
    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>


  <!-- Joint for Finger 1 Middle Segment -->
  <joint name="${prefix}joint_finger1_middle" type="revolute">
    <parent link="${prefix}finger1_base"/> <!-- Link to which the joint is connected -->
    <child link="${prefix}finger1_middle"/> <!-- Link that the joint connects to -->
    
    <!-- Joint origin and axis -->
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>

    <!-- Joint dynamics (optional) -->
    <dynamics damping="0.7"/>
    
    <!-- Joint limits -->
    <limit effort="100" velocity="1.0" lower="-3.14" upper="3.14"/>
  </joint>

  <!-- Finger 2 Base Link -->
  <link name="${prefix}finger2_base">
    <!-- Collision properties -->
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <!-- Visual properties -->
    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width*4} ${width*10} ${height1}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <!-- Inertial properties -->
    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>


  <!-- Joint for Finger 2 -->
  <joint name="${prefix}joint_finger2" type="revolute">
    <parent link="${prefix}base_link"/> <!-- Link to which the joint is connected -->
    <child link="${prefix}finger2_base"/> <!-- Link that the joint connects to -->
    
    <!-- Joint origin and axis -->
    <origin xyz="0 -${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>

    <!-- Joint dynamics (optional) -->
    <dynamics damping="0.7"/>

    <!-- Joint limits -->
    <limit effort="100" velocity="1.0" lower="-3.14" upper="3.14"/>
  </joint>


  <!-- Finger 2 Middle Link -->
  <link name="${prefix}finger2_middle">
    <!-- Collision properties -->
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <!-- Visual properties -->
    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>

    <!-- Inertial properties -->
    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- Joint for Finger 2 Middle Segment -->
  <joint name="${prefix}joint_finger2_middle" type="revolute">
    <parent link="${prefix}finger2_base"/> <!-- Link to which the joint is connected -->
    <child link="${prefix}finger2_middle"/> <!-- Link that the joint connects to -->
    
    <!-- Joint origin and axis -->
    <origin xyz="0 -${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>

    <!-- Joint dynamics (optional) -->
    <dynamics damping="0.7"/>

    <!-- Joint limits -->
    <limit effort="100" velocity="1.0" lower="-3.14" upper="3.14"/>
  </joint>


  <!-- Finger 3 Base Link -->
  <link name="${prefix}finger3_base">
    <!-- Collision properties -->
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <!-- Visual properties -->
    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width*4} ${width*10} ${height1}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <!-- Inertial properties -->
    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>


  <!-- Joint for Finger 3 -->
  <joint name="${prefix}joint_finger3" type="revolute">
    <parent link="${prefix}base_link"/> <!-- Link to which the joint is connected -->
    <child link="${prefix}finger3_base"/> <!-- Link that the joint connects to -->
    
    <!-- Joint origin and axis -->
    <origin xyz="0 ${width+0.5} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>

    <!-- Joint dynamics (optional) -->
    <dynamics damping="0.7"/>

    <!-- Joint limits -->
    <limit effort="100" velocity="1.0" lower="-3.14" upper="3.14"/>
  </joint>

  <!-- Finger 3 Middle Link -->
  <link name="${prefix}finger3_middle">
    <!-- Collision properties -->
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <!-- Visual properties -->
    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="yellow"/>
    </visual>

    <!-- Inertial properties -->
    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- Joint for Finger 3 Middle Segment -->
  <joint name="${prefix}joint_finger3_middle" type="revolute">
    <parent link="${prefix}finger3_base"/> <!-- Link to which the joint is connected -->
    <child link="${prefix}finger3_middle"/> <!-- Link that the joint connects to -->
    
    <!-- Joint origin and axis -->
    <origin xyz="0 ${width+0.5} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>

    <!-- Joint dynamics (optional) -->
    <dynamics damping="0.7"/>

    <!-- Joint limits -->
    <limit effort="100" velocity="1.0" lower="-3.14" upper="3.14"/>
  </joint>

  </xacro:macro>
</robot>
