controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController


forward_position_controller:
  ros__parameters:
    joints:
    - index_yaw________
    - middle_knuckle___
    - index_tip________
    - middle_yaw_______
    - pinky_knuckle____
    - pinky_pitch______
    - index_pitch______
    - wrist_yaw________
    - middle_tip_______
    - wrist_pitch_upper
    - wrist_pitch_lower
    - pinky_tip________
    - thumb_knuckle____
    - middle_pitch_____
    - ring_pitch_______
    - ring_knuckle_____
    - thumb_tip________
    - thumb_yaw________
    - thumb_roll_______
    - thumb_pitch______
    - ring_yaw_________
    - ring_tip_________
    - index_knuckle____
    - pinky_yaw________

    interface_name: position


joint_trajectory_position_controller:
  ros__parameters:
    joints:
      - index_yaw________
      - middle_knuckle___
      - index_tip________
      - middle_yaw_______
      - pinky_knuckle____
      - pinky_pitch______
      - index_pitch______
      - wrist_yaw________
      - middle_tip_______
      - wrist_pitch_upper
      - wrist_pitch_lower
      - pinky_tip________
      - thumb_knuckle____
      - middle_pitch_____
      - ring_pitch_______
      - ring_knuckle_____
      - thumb_tip________
      - thumb_yaw________
      - thumb_roll_______
      - thumb_pitch______
      - ring_yaw_________
      - ring_tip_________
      - index_knuckle____
      - pinky_yaw________
      

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
