publisher_forward_position_controller:
  ros__parameters:
    wait_sec_between_publish: 5
    publish_topic: "/forward_position_controller/commands"

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.785, 0.785, 0, 0, 0, 0, 0, 0, 0, 0]
    pos2: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    pos3: [-0.785, -0.785, 0, 0, 0, 0, 0, 0, 0, 0]
    pos4: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

    joints:
      - index_knuckle
      - index_pitch
      - index_tip
      - index_yaw
      - middle_knuckle
      - middle_pitch
      - middle_tip
      - middle_yaw
      - pinky_knuckle
      - pinky_pitch
      - pinky_tip
      - pinky_yaw
      - ring_knuckle
      - ring_pitch
      - ring_tip
      - ring_yaw
      - thumb_knuckle
      - thumb_pitch
      - thumb_roll
      - thumb_tip
      - thumb_yaw
      - wrist_pitch_lower
      - wrist_pitch_upper
      - wrist_yaw
