controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController


forward_position_controller:
  ros__parameters:
    joints:
      - index_knuckle
      - index_pitch
      - index_tip
      - index_yaw
      - middle_knuckle
      - middle_pitch
      - middle_tip
      - middle_yaw
      - pinky_knuckle
      - pinky_pitch
      - pinky_tip
      - pinky_yaw
      - ring_knuckle
      - ring_pitch
      - ring_tip
      - ring_yaw
      - thumb_knuckle
      - thumb_pitch
      - thumb_roll
      - thumb_tip
      - thumb_yaw
      - wrist_pitch_lower
      - wrist_pitch_upper
      - wrist_yaw
    interface_name: position


joint_trajectory_position_controller:
  ros__parameters:
    joints:
      - index_knuckle
      - index_pitch
      - index_tip
      - index_yaw
      - middle_knuckle
      - middle_pitch
      - middle_tip
      - middle_yaw
      - pinky_knuckle
      - pinky_pitch
      - pinky_tip
      - pinky_yaw
      - ring_knuckle
      - ring_pitch
      - ring_tip
      - ring_yaw
      - thumb_knuckle
      - thumb_pitch
      - thumb_roll
      - thumb_tip
      - thumb_yaw
      - wrist_pitch_lower
      - wrist_pitch_upper
      - wrist_yaw
      

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
