publisher_joint_trajectory_controller:
  ros__parameters:
    controller_name: "joint_trajectory_position_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.785, 0.785]
    pos2: [0, 0]
    pos3: [-0.785, -0.785]
    pos4: [0, 0]

    joints:
      - joint_finger_1_base
      - joint_finger_1_top
      - joint_finger_2_base
      - joint_finger_2_top
      - joint_finger_3_base
      - joint_finger_3_top
      - joint_finger_4_base
      - joint_finger_4_top
      - joint_thumb_base
      - joint_thumb_top

    check_starting_point: false
    starting_point_limits:
      joint_finger_1_base: [-0.1, 0.1]
      joint_finger_1_top: [-0.1, 0.1]
      joint_finger_2_base: [-0.1, 0.1]
      joint_finger_2_top: [-0.1, 0.1]
      joint_finger_3_base: [-0.1, 0.1]
      joint_finger_3_top: [-0.1, 0.1]
      joint_finger_4_base: [-0.1, 0.1]
      joint_finger_4_top: [-0.1, 0.1]
      joint_thumb_base: [-0.1, 0.1]
      joint_thumb_top: [-0.1, 0.1]
